version: 0.0
os: linux
files:
  - source: .
    destination: /opt/Temp_Location

permissions:
  - object: /opt/
    pattern: "**"
    owner: root
    group: root
    mode: 755
    type:
      - directory
hooks:
  BeforeInstall:
  - location: scripts/BACKUP.sh
    timeout: 100
    runas: root
  AfterInstall:
  - location: scripts/ROLLBACK.sh
    timeout: 300
    runas: root
