#---------------------------------------------------------------------
# GitHub Action Workflow to Deploy Flask App to AWS ElasticBeanstalk
#
# Version      Date        Info
# 1.0          2019        Initial Version
#
# Made by Denis Astahov ADV-IT Copyleft (c) 2019
#---------------------------------------------------------------------
name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "flash-github"
# APPLICATION_NAME          : "sampleapp"
#  APPLICATION_GROUP_NAME    : "samplegroup"
  DEPLOY_PACKAGE_NAME       : "flash-github-${{ github.sha }}.war"
  AWS_REGION_NAME           : "us-east-1"

on: 
  push:
    branches:
     - master

jobs:
    my_ci_pipeline:
       runs-on: ubuntu-latest
       steps:
         - name: Pre-build operation
           run: ./Building_Patch_Files.sh
           
         - name: Git clone our repository
           uses: actions/checkout@v1
         - name: Run CodeBuild
           uses: aws-actions/aws-codebuild-run-build@v1.0.3
           with:
             project-name: CodeBuildProjectName
             buildspec-override: ./buildspec.yaml
             env-vars-for-codebuild: |
              custom,
              requester,
              event-name
           env:
             custom: my environment variable
             requester: ${{ github.actor }}
             event-name: ${{ github.event_name }}
            
         - name: Create War deployment package
           run : war -r ${{ env.DEPLOY_PACKAGE_NAME }} ./  -x  *.git*
           
         - name: Configure my AWS Credentils
           uses: aws-actions/configure-aws-credentials@v1
           with:
             aws-access-key-id    : ${{ secrets.MY_AWS_ACCESS_KEY }}
             aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
             aws-region           : ${{ env.AWS_REGION_NAME }}
       
         - name: Copy our Deployment package to S3 bucket
           run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME}}/
         
         - name: Print nice message on completion of CI Pipeline
           run : echo "CI Pipeline part finished successfully"
    my_cd_pipeline:
       runs-on: ubuntu-latest
       needs: [my_ci_pipeline]
       if: github.ref == 'refs/heads/master'
       steps:
        - name: AWS Create Deploy
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id      : ${{ secrets.MY_AWS_ACCESS_KEY }}
            aws-secret-access-key  : ${{ secrets.MY_AWS_SECRET_KEY }}
            aws-region             : ${{ env.AWS_REGION_NAME }}
        - name: deployment in instances
          run:
             aws deploy create-deployment
               --application-name sampleapp
               --deployment-config-name CodeDeployDefault.OneAtATime
               --deployment-group-name groupapp
               --file-exists-behavior OVERWRITE
               --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
       
        - name: Print nice message on completion of CD Pipeline
          run : echo "CD Pipeline part finished successfully"  
